name: branch build
on: [push]
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.2
          poetry_version: 1.0.5
          args: install
      - name: run tests
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.2
          poetry_version: 1.0.5
          args: run python -m pytest
