name: branch build
on: [pull_request]
jobs:
  pytest:
    name: Branch Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.2
      - name: install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: poetry install
        run: |
          poetry install
      - name: lint
        run: |
          poetry run flake8 edina_garbage --show-source --statistics
          poetry run flake8 tests --show-source --statistics
      - name: pytest
        run: |
          poetry run pytest
