name: branch build
on: [pull_request]
jobs:
  pytest:
    name: Python Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.2
      - name: install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: poetry install
        run: |
          poetry install
      - name: lint
        run: |
          poetry run flake8 edina_garbage --show-source --statistics
          poetry run flake8 tests --show-source --statistics
      - name: pytest
        run: |
          poetry run pytest
  terraform:
    name: Terraform Verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: verify terraform
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "validate"
